data:
  input:
    data_path: 'C:/Users/zjc10/Desktop/Projects/data/cfpb/cfpb_complaints.csv'
  output: 
    data_save_dir: "C:/Users/zjc10/Desktop/Projects/data/semantic_search/output"
    
model:
  model_save_dir: "C:/Users/zjc10/Desktop/Projects/data/semantic_search/models"
  llm_model_name:  'BeIR/query-gen-msmarco-t5-large-v1'
  bi_encoder_model_name: 'msmarco-distilroberta-base-v3' #msmarco-distilbert-base-v2#'microsoft/mpnet-base'
  n_epochs: 1
  n_samps: 1000

  tokenizer: 
    return_tensors: 'pt'
    padding: 'max_length'
    return_overflow_tokens: True
    max_seq_len: 200
    truncation: True
    stride: 60
    batch_size: 10
  
  query_gen: 
    model_name: 'BeIR/query-gen-msmarco-t5-large-v1'
    n_queries_per_passage: 3
    batch_size: 3

  ir: 
    bi_encoder: 
      model_name:  'microsoft/mpnet-base' 
      batch_size: 5
    
    cross_encoder:
      model_name: 'cross-encoder/ms-marco-TinyBERT-L-2-v2'

    faiss_index: 
      out_dir: "C:/Users/zjc10/Desktop/Projects/data/semantic_search/faiss_indicies"